version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_GOOGLE_MAPS_API_KEY=${VITE_GOOGLE_MAPS_API_KEY}
        - VITE_OPENWEATHER_API_KEY=${VITE_OPENWEATHER_API_KEY}
        - VITE_UNSPLASH_ACCESS_KEY=${VITE_UNSPLASH_ACCESS_KEY}
        - VITE_API_NINJAS_KEY=${VITE_API_NINJAS_KEY}
    ports:
      - "80:80"
    environment:
      - VITE_GOOGLE_MAPS_API_KEY=${VITE_GOOGLE_MAPS_API_KEY}
      - VITE_OPENWEATHER_API_KEY=${VITE_OPENWEATHER_API_KEY}
      - VITE_UNSPLASH_ACCESS_KEY=${VITE_UNSPLASH_ACCESS_KEY}
      - VITE_API_NINJAS_KEY=${VITE_API_NINJAS_KEY}
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped 